### ISSUE TITLE
Invalid string length exception on large reads

### ISSUE THREAD

**Issue by genzgd** [ClickHouse/clickhouse-js#106]
Crashes when reading 50,000,000 numbers (at least on my Mac M1).

Code to reproduce (against localhost/local docker):

```javascript
const { createClient } = require('@clickhouse/client')

(async () => {
    const client = createClient();
    console.log(Date.now() / 1000)
    const result = await client.query({
        query: 'SELECT number FROM numbers(50000000)',
        format: "JSONCompactEachRow"
    });
    console.log(Date.now() / 1000);
    const stuff = await result.json();
    console.log(stuff.length);
    console.log(Date.now() / 1000);

})()
```

Exception:

```
1664586660.882
1664586660.895
AbortError: The operation was aborted
    at Object.destroyer (node:internal/streams/destroy:305:11)
    at createAsyncIterator (node:internal/streams/readable:1141:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'ABORT_ERR'
}
/Users/geoff/projects/nodetests/node_modules/@clickhouse/client/dist/utils/stream.js:16
        result += textDecoder.decode(chunk, { stream: true });
                              ^

RangeError: Invalid string length
    at getAsText (/Users/geoff/projects/nodetests/node_modules/@clickhouse/client/dist/utils/stream.js:16:31)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Rows.text (/Users/geoff/projects/nodetests/node_modules/@clickhouse/client/dist/rows.js:37:17)
    at async Rows.json (/Users/geoff/projects/nodetests/node_modules/@clickhouse/client/dist/rows.js:50:45)
    at async /Users/geoff/projects/nodetests/index.js:47:19

Node.js v18.9.0
```

**Comment by slvrtrn** [comment]
Unfortunately, that seems to be a hard Node.js limitation. We cannot use strings larger than 512Mb at the moment. If I understand it correctly, it was increased from 256Mb to 1Gb in the past and then reduced to 512Mb.

See 
- https://stackoverflow.com/questions/44533966/v8-node-js-increase-max-allowed-string-length
- https://github.com/nodejs/help/issues/712#issuecomment-582709275
- https://github.com/v8/v8/commit/ea56bf5513d0cbd2a35a9035c5c2996272b8b728 

My tests showed that it indeed crashes at around 512Mb of size, with the resulting string's length around 536870888.

**Comment by ck-clickhouse** [comment]
Hi @slvrtrn , a customer recently faced this issue and as a workaround they tried converting arrays to stream, that worked but the inserts got 5-10x slower. Is that expected or is there a better alternative than having smaller batches?
