### ISSUE TITLE
Can't use your package with Yandex.Cloud managed clickhouse

### ISSUE THREAD

**Issue by bytadaniel** [ClickHouse/clickhouse-js#115]
Please add certificate support like there https://www.npmjs.com/package/clickhouse-ts
Some managed services such as yandex cloud, amazon aws etc require using certificate to confirm the query's source.

**Comment by bytadaniel** [comment]
I'd like to switch to your client in my work projects, but either haven't figured out how to pass the certificate, or it's not implemented yet😅

**Comment by slvrtrn** [comment]
Hi @bytadaniel, thanks for reaching out.
We have this feature in our backlog: https://github.com/ClickHouse/clickhouse-js/issues/52
As I see that there is demand now, it will be implemented in the scope of the next version release (which is _soon_)
Please stay tuned!

**Comment by slvrtrn** [comment]
@bytadaniel SSL/TLS support was implemented in 0.0.8. 
Check out the examples - [basic](https://github.com/ClickHouse/clickhouse-js/blob/main/examples/basic_tls.ts), [mutual](https://github.com/ClickHouse/clickhouse-js/blob/main/examples/mutual_tls.ts).
I tested it with Yandex cloud (adding username and password to the config), works fine. 
Please feel free to open a new issue if you find any bugs. 
Cheers.
