### ISSUE TITLE
Authentication failed: password is incorrect or there is no user with such name. 

### ISSUE THREAD

**Issue by SimonHausdorf** [ClickHouse/clickhouse-js#126]
Working curl example
```bash
echo 'SELECT version()' | curl 'https://analytics:analytics3113@***:8123/?database=analytics' --data-binary @-
```

Error throwing javascript example
```javascript
const client = createClient({
  host: "https://***:8123",
  username: "analytics",
  password: "analytics3113",
  database: "analytics",
});
```

Error
```
error: Uncaught Error: default: Authentication failed: password is incorrect or there is no user with such name.
```

In both cases da domain was used with valid ssl certificate.

**Comment by slvrtrn** [comment]
Hmm, that's hard to tell straight away what might be wrong here. 
But the port looks a bit odd, it is usually 8443 instead of 8123 for HTTPS.
I assume this is a self-hosted configuration?

**Comment by SimonHausdorf** [comment]
True, should be 8443, however, with 8123 / http I am getting the same error.

My endpoint `http://***:8123` returns `Ok.`

curl
```bash
➜  ~ echo 'SELECT version()' | curl 'http://analytics:analytics3113@***:8123/?database=analytics' --data-binary @-
22.11.2.30
```

working javascript connection
```javascript
const db = createClient({
  host: "http://analytics:analytics3113@***:8123",
  // username: "analytics",
  // password: "analytics3113",
  database: "analytics",
});
```

not working connection
```javascript
const client = createClient({
  host: "http://***:8123",
  username: "analytics",
  password: "analytics3113",
  database: "analytics",
});
```

Error
```
error: Uncaught Error: default: Authentication failed: password is incorrect or there is no user with such name. 
```

**Comment by slvrtrn** [comment]
I'd appreciate it if you could join our [community slack](https://clickhousedb.slack.com/join/shared_invite/zt-nwwakmk4-xOJ6cdy0sJC3It8j348~IA#/) and share your server configuration and exact code snippets with me there. It will help with the debugging of this scenario.

**Comment by SimonHausdorf** [comment]
Issue seems to be with Deno. I am not sure what exactly causes the problem but it doesn't seem to be a direct issue with ClickHouse javascript module.
