### ISSUE TITLE
not work on https clickhouse

### ISSUE THREAD

**Issue by alibeknow** [ClickHouse/clickhouse-js#145]
### Steps to reproduce
1.  this.client = createClient(options);
2. its work on http client, but not work in https client
3.

#### Environment
* Client version:   "@clickhouse/client": "^0.0.12",
* Language version: node js 16.16
* OS: windows/linux

#### ClickHouse server
* ClickHouse Server version:  23.1.3
* ClickHouse Server non-default settings, if any:
* `CREATE TABLE` statements for tables involved: can't do anything recieve not expected error can't parse data from JSONEACHROW, but problem is in connection
* Sample data for all these tables, use [clickhouse-obfuscator](https://github.com/ClickHouse/ClickHouse/blob/master/programs/obfuscator/Obfuscator.cpp#L42-L80) if necessary

**Comment by slvrtrn** [comment]
1. How do you create a client? Usually, it should work as 
```ts
const client = createClient({
  host: 'https://<hostname>:<port>',
  username: '<username>',
  password: '<password>',
})
```
2. Does your server require TLS? If so, please check out the [certificates usage docs](https://clickhouse.com/docs/en/integrations/language-clients/nodejs#tls-certificates), and [sample code](https://github.com/ClickHouse/clickhouse-js/blob/main/examples/basic_tls.ts))
