### ISSUE TITLE
Problem with parsing not standard queries

### ISSUE THREAD

**Issue by p-pekala** [ClickHouse/clickhouse-js#173]
### Describe the bug

It is not possible to execute `SYSTEM RELOAD DICTIONARIES` or `TRUNCATE` queries

### Expected behaviour

Queries should be supported.

### Code example

          await clickhouseClient.query({
            query: `SYSTEM RELOAD DICTIONARIES`,
          });

### Error log

Syntax error: failed at position 29 ('FORMAT') (line 2, col 1): FORMAT JSON. Expected one of: ON, end of query.

**Comment by slvrtrn** [comment]
https://clickhouse.com/docs/en/integrations/language-clients/nodejs#command-method

**Comment by p-pekala** [comment]
My bad, I missed the difference in the method name. Thank you

**Comment by calebeaires** [comment]
To deal with this, I simply use the ".query" command. Then, I verify if there is a JSON present. Although it could be improved, it currently serves its purpose.


```js

                            const result = await resultSet.text();

                            if (result) {
                                return resolve(JSON.parse(result));
                            } else {
                                return resolve({ command: 'success' });
                            }
```
