### ISSUE TITLE
Temporary Table unusable from client

### ISSUE THREAD

**Issue by ArmyDev** [ClickHouse/clickhouse-js#194]
To trigger the error: `ClickHouseError: Table data.test doesn't exist`
You have to initialise a client, create a temporary table and then try getting any data out of it.

The following is the code I used to trigger the error

```js
(async () => {

  const client = createClient({
      // ...settings
      database: 'data',
  });
  
  await client.command({
      query: `
        CREATE TEMPORARY TABLE test (
          url String,
          timestamp Float64
        );
      `,
  });
  
  await client.query({
      query: `
        SELECT * FROM test;
      `,
  });

})();
```

**Comment by slvrtrn** [comment]
You need to include a session id. See the related test: https://github.com/ClickHouse/clickhouse-js/blob/b38613832b70e7b8744d15b9a0914e264cc7e747/packages/client-common/__tests__/integration/exec.test.ts#L75-L95

**Comment by ArmyDev** [comment]
Thank you

**Comment by slvrtrn** [comment]
@ArmyDev, no worries, I've added an example now: https://github.com/ClickHouse/clickhouse-js/blob/main/examples/session_id_and_temporary_tables.ts
