### ISSUE TITLE
Can't specify `default_format` parameter

### ISSUE THREAD

**Issue by mshustov** [ClickHouse/clickhouse-js#198]
`database` and `default_format` are special parameters that shouldn't be prefixed with `param_`.
https://github.com/ClickHouse/ClickHouse/blob/0907623c9dea4600fe4c72a129fe5b7b26d82754/src/Server/HTTPHandler.cpp#L736-L747

https://github.com/ClickHouse/clickhouse-js/blob/c8f24d72c0823ff76f291433d47274df9ec11b64/packages/client-common/src/utils/url.ts#L58

**Comment by slvrtrn** [comment]
I think #200 closes this.
