### ISSUE TITLE
Type bug with insert

### ISSUE THREAD

**Issue by paymog** [ClickHouse/clickhouse-js#199]
### Describe the bug

I would expect the following code to have type issues

```ts
  import { createClient } from "@clickhouse/client";

  const clickhouseClient = createClient({
    host: CLICKHOUSE_URL,
    username: CLICKHOUSE_USER,
    password: CLICKHOUSE_PASSWORD,
    application: "my-application",
    database: CLICKHOUSE_DATABASE,
  });

  await clickhouseClient.insert<{ a: number }>({
    table: CLICKHOUSE_SUBGRAPH_STATUS_TABLE,
    format: "JSONEachRow",
    values: statuses.map((status) => ({
      db_name: status.dbName,
      ipfs_hash: status.ipfsHash,
      synced: status.synced,
      failed: status.failed,
    })),
  });
```

and when I hover of `values` in my IDE I’m told it has a type of `unknown`

<img width="468" alt="image" src="https://github.com/ClickHouse/clickhouse-js/assets/1986950/8396429b-0d3b-419d-8ff5-74f6526194da">

### Expected behaviour

I expect the generic of the `insert` method to be applied to the shape of the args for the `values` property

#### Environment
* Client version: `^0.2.0`

**Comment by paymog** [comment]
> Can you please provide the entire code snippet, including imports?

I just updated the code snippet with more context. If you need more information please let me know.

**Comment by slvrtrn** [comment]
Yep, it does not reproduce on my machine as well. For example:

![image](https://github.com/ClickHouse/clickhouse-js/assets/3175289/c8ed7af4-af65-4ae7-acea-4a8ab1ea9f87)

TS 4.9.5
[tsconfig.json](https://github.com/ClickHouse/clickhouse-js/blob/main/tsconfig.json)

**Comment by paymog** [comment]
I think I got it. I was trying to simplify the code in the example. Here's a much fuller code sample which had the issue:

```ts
async function saveStatusesToDb(
  statuses: SubgraphStatus[],
  clickhouseClient: ClickHouseClient,
  logger: Logger
) {
  // stuff
  await clickhouseClient.insert<{ a: number }>({
    table: CLICKHOUSE_SUBGRAPH_STATUS_TABLE,
    format: "JSONEachRow",
    values: statuses.map((status) => ({
      db_name: status.dbName,
      ipfs_hash: status.ipfsHash,
      synced: status.synced,
      failed: status.failed,
    })),
  });
}
```

When I hovered over the `clickhouseClient` I saw that it had a generic of `unknown`

<img width="503" alt="image" src="https://github.com/ClickHouse/clickhouse-js/assets/1986950/48f33352-315d-48bc-b68a-a1d063c307c4">

I checked the repl and saw that the client had a generic of `Readable`

<img width="532" alt="image" src="https://github.com/ClickHouse/clickhouse-js/assets/1986950/3db2b385-ecec-4a72-b267-b0edbff05ba8">

When I update my function parameter declaration like so (with a `<Readable>` generic)

```ts
async function saveStatusesToDb(
  statuses: SubgraphStatus[],
  clickhouseClient: ClickHouseClient<Readable>,
  logger: Logger
```

The types start getting inferred correctly

<img width="590" alt="image" src="https://github.com/ClickHouse/clickhouse-js/assets/1986950/bb9c94e6-1611-4ac9-b222-9099ce0f2ee3">

**Comment by paymog** [comment]
So tldr: when accepting a client as a function parameter, it must be typed with a `<Readable>` generic for the type system to work properly. Not sure why that's the case.

**Comment by slvrtrn** [comment]
Yep, `ClickHouseClient` is now (after 0.2.0) a generic type with different stream types depending on the implementation.
