### ISSUE TITLE
Provide a version for browser environment 

### ISSUE THREAD

**Issue by mshustov** [ClickHouse/clickhouse-js#2]
The browser version of the client can provide limited functionality but with a similar API.
The integration tests must be run in both `nodejs` and `browser` envs.

In the first implementation, the client uses `webpack` to shim `http` module with a browser-compatible version. This approach doesn't allow us to implement env-specific logic for the network modules, so let's consider implementing a separate `http_browser_adapter` that might encapsulate browser-specific network logic. The separation can be done on the code level by using a dedicated `browser` entry point of `package.json` see https://docs.npmjs.com/cli/v8/configuring-npm/package-json#browser

**Comment by slvrtrn** [comment]
Closing this as #165 was merged; we also have this now: #162
