### ISSUE TITLE
Allow direct usage of Date objects for inserts

### ISSUE THREAD

**Issue by aimfeld** [ClickHouse/clickhouse-js#215]
I'm using clickhouse-js to insert rows into a table. For timestamps, I'm using  `DateTime64(3, 'UTC')`. However, the client seems to have a problem with Date objects:
`Cannot parse input: expected '"' before: 'Z","message":"{\\"created_at\\":\\"2023-12-06T10:54:48.000Z\\",\\"modified_at\\":\\"2023-12-': (while reading the value of key created_at): While executing ParallelParsingBlockInputFormat: (at row 1) ... ,"error":{"code":"27","type":"CANNOT_PARSE_INPUT_ASSERTION_FAILED"}`

When I convert the Date objects to strings and remove the timezone part, it works:

```typescript
import { ClickHouseClient } from '@clickhouse/client';
import { InsertClient } from './InsertClient';
import moment from 'moment';

export class ClickHouseInsertClient implements InsertClient {
    public constructor(private clickHouseClient: ClickHouseClient) {}

    public async insertObjects(tableName: string, objects: object[]): Promise<void> {
        for (const object of objects) {
            for (const key of Object.keys(object)) {
                object[key] = this.sanitizeValue(object[key]);
            }
        }
        await this.clickHouseClient.insert({
            table: tableName,
            values: objects,
            format: 'JSONEachRow'
        });
    }

    private sanitizeValue(value: unknown): unknown {
        // ClickHouse can't handle the timezone part (Z or offset +00:00) in the date string
        if (value instanceof Date) {
            return moment(value).format('YYYY-MM-DD HH:mm:ss.SSS');
        }
        return value;
    }
}
```

#### Environment
* Client version: 0.2.6
* Language version:
* OS: Linux

#### ClickHouse server
* ClickHouse Server version: 23.9.1.1854

**Comment by mshustov** [comment]
consider using [date_time_input_format= best_effort](https://clickhouse.com/docs/en/operations/settings/formats#date_time_input_format)

**Comment by slvrtrn** [comment]
@mshustov, thanks! It works very well with DateTime fields (see the [test](https://github.com/ClickHouse/clickhouse-js/blob/df4839d1e48a38d66865f90e673d20cc2ae6d54d/packages/client-common/__tests__/integration/data_types.test.ts#L173-L215)). Date/Date32 are not parsed properly with this setting, though; I think we can revisit it in the scope of https://github.com/ClickHouse/clickhouse-js/issues/216

@aimfeld, I added an [example](https://github.com/ClickHouse/clickhouse-js/blob/main/examples/insert_js_dates.ts) that should work for your use-case. Feel free to re-open or DM in the community Slack if you encounter any issues.

**Comment by aimfeld** [comment]
@slvrtrn It works, thanks for the quick fix!
