### ISSUE TITLE
Getting "Error: Cannot modify 'enable_http_compression' setting in readonly mode."

### ISSUE THREAD

**Issue by 0xStrobe** [ClickHouse/clickhouse-js#221]
I have a readonly user which I want to use this client library to connect with. I'm getting this error on any requests sent, and I'm not so sure how to move forward.

I tried creating the clickhouse client objects with `enable_http_compression` set to both 1 or 0. However it still throws that error.

```js
const client = createClient({
    host: process.env.CLICKHOUSE_HOST,
    username: process.env.CLICKHOUSE_USERNAME,
    password: process.env.CLICKHOUSE_PASSWORD,
    clickhouse_settings: {
      enable_http_compression: 1, // 0 doesn't work either
    },
  }),
```

My `enable_http_compression` setting in Clickhouse is `0`.

How can I fix this and connect to my DB using a readonly user?

Additionally, slightly out of scope - how to change this setting on the db side? The docs are a little vague - I'm aware that this setting is a part of the `http` interface, but it's unclear to me if and how I could change it in the XML file. Which section of this setting belongs to? I tried to change it via SQL commands `SET enable_http_compression=1;`, but there seems to be no effects.

**Comment by slvrtrn** [comment]
Just noticed this issue (I didn't get a notification for a closed one for some reason).
I've recently added a runnable [read-only user example](https://github.com/ClickHouse/clickhouse-js/blob/927ca276d4d41d44e6b36b4315c5143a3467258a/examples/read_only_user.ts) which might help if it is still an issue.
