### ISSUE TITLE
Add connection url support to the client

### ISSUE THREAD

**Issue by PmegaOcalc** [ClickHouse/clickhouse-js#228]
### Use case

We set database environment variables based on the standard format of xxx://[userspec@][hostspec][/dbname][?paramspec]
Clickhouse js client currently doesn't support it and we need to specify the env variables inconsistently to other databases.

### Describe the solution you'd like

Add support for connection string like clickhouse://[user_info@][hosts_and_ports][/dbname][?query_parameters]
as it is already supported in clickhouse https://github.com/ClickHouse/ClickHouse/pull/50689

### Additional context

ClickHouseClientConfigOptions defines the connection options

**Comment by slvrtrn** [comment]
I will add URL support for `http[s]://[username]:[password]@[host]:[port]/[database]` in the next version and deprecate `host` (that was not the best name for it).

**Comment by slvrtrn** [comment]
@PmegaOcalc, will be included in 1.0.0, ETA ~few weeks.

**Comment by slvrtrn** [comment]
@PmegaOcalc, [1.0.0](https://github.com/ClickHouse/clickhouse-js/releases/tag/1.0.0) is out; URL configuration is supported now.
