### ISSUE TITLE
Bun: ClickHouse DB not connecting

### ISSUE THREAD

**Issue by nmdaniil** [ClickHouse/clickhouse-js#260]
# Using [Bun](https://bun.sh/) instead of nodejs it doesn't work

## What version of Bun is running?*
`1.0.1`

## What platform is your computer?
- Linux 5.15.90.1-microsoft-standard-WSL2 x86_64 x86_64
- MacOs 
- and etc

## What steps can reproduce the bug?
```javascript
import { createClient } from "@clickhouse/client";

console.log('connecting ClickHouse DB ...')
const CHDB = createClient({
    host: config.database.chdb.host,
    username: config.database.chdb.user,
    password: config.database.chdb.password,
    database: config.database.chdb.database
});
console.log(await CHDB.ping());
```

## What is the expected behavior?
```
connecting ClickHouse DB ...
{ success: true }
```

## What do you see instead?
```
connecting ClickHouse DB ...
```
Additional information
It just hangs and laptop fan starts to make high noise.

Before bun 1.0, it used to crash with only "Segmentation Fault" in console.

**Comment by slvrtrn** [comment]
Does it work if you use `@clickhouse/client-web` instead of `@clickhouse/client`?

**Comment by slvrtrn** [comment]
Related: https://github.com/ClickHouse/clickhouse-js/issues/211

**Comment by nmdaniil** [comment]
Dear gentlemen, I wanted to please you that in the new **version (~1.1.13+)** of the **Bun** the library is working
