### ISSUE TITLE
Inserting decimal numbers using NodeJs client

### ISSUE THREAD

**Issue by kevcodez** [ClickHouse/clickhouse-js#261]
According to the [docs](https://clickhouse.com/docs/en/integrations/language-clients/javascript#decimal-types-caveats), we're not supposed to use JSON strings but Tab/CSV separated with the following code

```
await client.insert({
  table: 'my_table',
  values: ['12.01\t5000000.405\n'],
  format: 'TabSeparated',
})
```

However, this results in the error:

> The client does not support JSON encoding in [TabSeparated] format.

If I take it correctly from the [docs](https://clickhouse.com/docs/en/integrations/language-clients/javascript#supported-data-formats), it's not possibly to use TabSeparated / CsvSeparated to insert an array of strings?

Am I missing something here?

**Comment by slvrtrn** [comment]
For "raw" formats, a stream is required as the input. 
You could create it from an array, similarly to how it is done in this example: https://github.com/ClickHouse/clickhouse-js/blob/main/examples/node/stream_created_from_array_raw.ts#L23-L30. 
Please ignore the typo about the format in the comment. 
CSV/TabSepated/CustomSeparated all work the same way.

**Comment by slvrtrn** [comment]
This bit regarding decimals and JSON seems very outdated. 
_Maybe_ it was an issue a while ago when we started the project and wrote the initial docs, but as of the current CH versions, it's all good. I will update the docs.

So, it works fine with JSONEachRow. I pushed an example: https://github.com/ClickHouse/clickhouse-js/blob/main/examples/insert_decimals.ts

**Comment by slvrtrn** [comment]
Docs will be updated when this PR is merged: https://github.com/ClickHouse/clickhouse-docs/pull/2207
