### ISSUE TITLE
BaseQueryParams.session_id is not used

### ISSUE THREAD

**Issue by Holi0317** [ClickHouse/clickhouse-js#271]
### Describe the bug

`BaseQueryParams` got an [undocumented `session_id`](https://github.com/ClickHouse/clickhouse-js/blob/ad8611e736a82d98416c1d99d903240df02d7ace/packages/client-common/src/client.ts#L28) that feels like it should override the `session_id` passed into `createClient`. But actually that field is never used and `session_id` is always using `this.sessionId` https://github.com/ClickHouse/clickhouse-js/blob/ad8611e736a82d98416c1d99d903240df02d7ace/packages/client-common/src/client.ts#L253

### Steps to reproduce
1. Try to override `session_id` via `BaseQueryParams`

### Expected behaviour

The `session_id` should be overridden

**Comment by slvrtrn** [comment]
Added in [1.1.0](https://github.com/ClickHouse/clickhouse-js/releases/tag/1.1.0).
