### ISSUE TITLE
Extend the list of supported formats 

### ISSUE THREAD

**Issue by mshustov** [ClickHouse/clickhouse-js#28]
Add `JSON*`, `CSV*`, `TabSeparated*` formats that can be supported by the client in the current implementation https://github.com/ClickHouse/clickhouse-js/blob/6caae6067928700847a524793d8db535cd631976/src/data_formatter/formatter.ts#L2-L22
https://clickhouse.com/docs/en/interfaces/formats/

- [x] JSON
- [x] CSV
- [x] TSV
- [x] Custom separated

**Comment by slvrtrn** [comment]
JSON formats for streaming are fully covered in #83
