### ISSUE TITLE
BaseClickHouseClientConfigOptions interface should define keep_alive. idle_socket_ttl

### ISSUE THREAD

**Issue by brian-mann** [ClickHouse/clickhouse-js#303]
### Expected behaviour

Per the official docs there is a `keep_alive.idle_socket_ttl` that's should be configurable.

https://clickhouse.com/docs/en/integrations/language-clients/javascript#keep-alive-configuration-nodejs-only

However the types only have the `keep_alive.enabled` property, it's missing `idle_socket_ttl` per this file:

https://github.com/ClickHouse/clickhouse-js/blob/main/packages/client-common/src/config.ts#L75-L79

**Comment by slvrtrn** [comment]
This is a Node.js-specific setting; the correct interface is [here](https://github.com/ClickHouse/clickhouse-js/blob/30ce583b8b530921ad12aa81e063a4910fa30317/packages/client-node/src/config.ts#L18-L43), which extends `BaseClickHouseClientConfigOptions`.

It is properly recognized by the IDE, e.g.:

<img width="665" alt="image" src="https://github.com/user-attachments/assets/e7c897db-ffbe-48f8-bc07-5544a36027b4">
