### ISSUE TITLE
Values for `User-Agent` set in `http_headers` are ignored

### ISSUE THREAD

**Issue by michaelsmithxyz** [ClickHouse/clickhouse-js#345]
Prior to [this PR](https://github.com/ClickHouse/clickhouse-js/pull/279/), which was released in version 1.1.0, supplying a value for  `User-Agent` in `http_headers` would override the user agent header sent by the client. As of that change, this no longer works. Rather an application default, which is somewhat but not fully customizable, is sent.

### Steps to reproduce
1. Set `User-Agent` in `http_headers` to some value
2. Observe in the ClickHouse query log that `http_user_agent` is set to a default value like `clickhouse-js/1.4.1 (lv:nodejs/v18.19.1; os:linux)`

### Expected behaviour

I would expect to be able to provide a fully custom `User-Agent` header

**Comment by slvrtrn** [comment]
That `clickhouse-js/1.4.1 (lv:nodejs/v18.19.1; os:linux)` part from the `User-Agent` header was never supposed to be completely overridden (so the linked PR, in fact, fixed the bug); however, it is still possible to attach additional information to it using the `application` configuration parameter.

e.g. 

```ts
const client = createClient({
  application: 'MyApp'
})
```

will result in the `User-Agent` header like the following:

```
MyApp clickhouse-js/1.7.0 (lv:nodejs/v20.10.0; os:linux)
```
