### ISSUE TITLE
NPM release GitHub action

### ISSUE THREAD

**Issue by slvrtrn** [ClickHouse/clickhouse-js#43]

**Comment by kamilkisiela** [comment]
I recommend https://github.com/changesets/changesets, we (The Guild) use it a lot, it comes with a changelog generation and new releases are done by merging a Pull Request (created by changesets).

Example pull request with a patch update:
https://github.com/kamilkisiela/graphql-hive/pull/399

Example pull request that releases a new version:
https://github.com/kamilkisiela/graphql-hive/pull/400

**Comment by slvrtrn** [comment]
@kamilkisiela thanks for the suggestion! 

This is definitely a good idea to use such a workflow if (when) we will have a higher volume of merged PRs over time. 

For now, I was thinking of something as simple as NPM publish triggered by tag creation with some manual changelog which should be not hard to compose.

**Comment by slvrtrn** [comment]
I've added [a simple NPM publish workflow](https://github.com/ClickHouse/clickhouse-js/blob/main/.github/workflows/release.yml).
