### ISSUE TITLE
Update license file 

### ISSUE THREAD

**Issue by mzitnik** [ClickHouse/clickhouse-js#62]
Please update the license file see: https://github.com/ClickHouse/clickhouse-js/blob/main/LICENSE#L189

You can just copy the [ClickHouse license file](https://github.com/ClickHouse/ClickHouse/blob/master/LICENSE)

**Comment by slvrtrn** [comment]
Closed by https://github.com/ClickHouse/clickhouse-js/commit/320cbf7429049c266d5195e1b2ff2d1c2e7e1aaf
